package pe.egcc.eureka.app.view;

import java.io.InputStream;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JInternalFrame;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import pe.egcc.eureka.app.db.AccesoDB;
import pe.egcc.eureka.app.domain.Empleado;
import pe.egcc.eureka.app.util.Memoria;
import pe.egcc.eureka.app.util.Mensaje;

/**
 *
 * @author Gustavo Coronel
 */
public class MainView extends javax.swing.JFrame {

  /**
   * Creates new form MainView
   */
  public MainView() {
    initComponents();
    this.setExtendedState(MAXIMIZED_BOTH);
    crearTitulo();
  }

  private void crearTitulo() {
    String titulo = "EUREKA APP [ Usuario: ";
    Empleado bean = (Empleado) Memoria.get("usuario");
    titulo += bean.getNombre() + " " + bean.getPaterno() + " ]";
    this.setTitle(titulo);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    desktopPane = new javax.swing.JDesktopPane();
    menuBar = new javax.swing.JMenuBar();
    fileMenu = new javax.swing.JMenu();
    openMenuItem = new javax.swing.JMenuItem();
    saveMenuItem = new javax.swing.JMenuItem();
    saveAsMenuItem = new javax.swing.JMenuItem();
    exitMenuItem = new javax.swing.JMenuItem();
    editMenu = new javax.swing.JMenu();
    cutMenuItem = new javax.swing.JMenuItem();
    copyMenuItem = new javax.swing.JMenuItem();
    pasteMenuItem = new javax.swing.JMenuItem();
    deleteMenuItem = new javax.swing.JMenuItem();
    helpMenu = new javax.swing.JMenu();
    contentMenuItem = new javax.swing.JMenuItem();
    aboutMenuItem = new javax.swing.JMenuItem();
    menuProcesos = new javax.swing.JMenu();
    menuProcesosCrearCuenta = new javax.swing.JMenuItem();
    menuProcesosDeposito = new javax.swing.JMenuItem();
    menuProcesosRetiro = new javax.swing.JMenuItem();
    menuProcesosTransferencia = new javax.swing.JMenuItem();
    menuTablas = new javax.swing.JMenu();
    menuTablasCliente = new javax.swing.JMenuItem();
    menuTablasSucursales = new javax.swing.JMenuItem();
    menuReportes = new javax.swing.JMenu();
    menuReportesClientes = new javax.swing.JMenuItem();
    menuReportesClientes2 = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("EUREKA");

    fileMenu.setMnemonic('f');
    fileMenu.setText("File");

    openMenuItem.setMnemonic('o');
    openMenuItem.setText("Open");
    fileMenu.add(openMenuItem);

    saveMenuItem.setMnemonic('s');
    saveMenuItem.setText("Save");
    fileMenu.add(saveMenuItem);

    saveAsMenuItem.setMnemonic('a');
    saveAsMenuItem.setText("Save As ...");
    saveAsMenuItem.setDisplayedMnemonicIndex(5);
    fileMenu.add(saveAsMenuItem);

    exitMenuItem.setMnemonic('x');
    exitMenuItem.setText("Exit");
    exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        exitMenuItemActionPerformed(evt);
      }
    });
    fileMenu.add(exitMenuItem);

    menuBar.add(fileMenu);

    editMenu.setMnemonic('e');
    editMenu.setText("Edit");

    cutMenuItem.setMnemonic('t');
    cutMenuItem.setText("Cut");
    editMenu.add(cutMenuItem);

    copyMenuItem.setMnemonic('y');
    copyMenuItem.setText("Copy");
    editMenu.add(copyMenuItem);

    pasteMenuItem.setMnemonic('p');
    pasteMenuItem.setText("Paste");
    editMenu.add(pasteMenuItem);

    deleteMenuItem.setMnemonic('d');
    deleteMenuItem.setText("Delete");
    editMenu.add(deleteMenuItem);

    menuBar.add(editMenu);

    helpMenu.setMnemonic('h');
    helpMenu.setText("Help");

    contentMenuItem.setMnemonic('c');
    contentMenuItem.setText("Contents");
    helpMenu.add(contentMenuItem);

    aboutMenuItem.setMnemonic('a');
    aboutMenuItem.setText("About");
    helpMenu.add(aboutMenuItem);

    menuBar.add(helpMenu);

    menuProcesos.setText("Procesos");

    menuProcesosCrearCuenta.setText("Crear cuenta");
    menuProcesos.add(menuProcesosCrearCuenta);

    menuProcesosDeposito.setText("Registrar depósito");
    menuProcesos.add(menuProcesosDeposito);

    menuProcesosRetiro.setText("Registrar retiro");
    menuProcesosRetiro.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuProcesosRetiroActionPerformed(evt);
      }
    });
    menuProcesos.add(menuProcesosRetiro);

    menuProcesosTransferencia.setText("Transferencia");
    menuProcesos.add(menuProcesosTransferencia);

    menuBar.add(menuProcesos);

    menuTablas.setText("Tablas");

    menuTablasCliente.setText("Clientes");
    menuTablasCliente.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuTablasClienteActionPerformed(evt);
      }
    });
    menuTablas.add(menuTablasCliente);

    menuTablasSucursales.setText("Sucursales");
    menuTablasSucursales.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuTablasSucursalesActionPerformed(evt);
      }
    });
    menuTablas.add(menuTablasSucursales);

    menuBar.add(menuTablas);

    menuReportes.setText("Reportes");

    menuReportesClientes.setText("Clientes");
    menuReportesClientes.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuReportesClientesActionPerformed(evt);
      }
    });
    menuReportes.add(menuReportesClientes);

    menuReportesClientes2.setText("Clientes 2");
    menuReportesClientes2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuReportesClientes2ActionPerformed(evt);
      }
    });
    menuReportes.add(menuReportesClientes2);

    menuBar.add(menuReportes);

    setJMenuBar(menuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
      System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

  private void menuTablasClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTablasClienteActionPerformed
    cargarVentana(MantClientesView.class);
  }//GEN-LAST:event_menuTablasClienteActionPerformed

  private void menuTablasSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTablasSucursalesActionPerformed
    cargarVentana(MantSucursalView.class);
  }//GEN-LAST:event_menuTablasSucursalesActionPerformed

  private void menuReportesClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesClientesActionPerformed
    Connection cn = null;
    try {
      // El objeto Connection
      cn = AccesoDB.getConnection();
      // Parametros
      Map pars = new HashMap();
      // logo
      String logo = "/pe/egcc/eureka/app/img/logo3.gif";
      InputStream logoStream = Class.class.getResourceAsStream(logo);
      pars.put("LOGO", logoStream);
      // Archivo JRXML
      String archivo = "/pe/egcc/eureka/app/reports/listadoClientes.jrxml";
      InputStream archivoStream = Class.class.getResourceAsStream(archivo);
      // Compilación y ejecución
      JasperReport report = JasperCompileManager.compileReport(archivoStream);
      JasperPrint print = JasperFillManager.fillReport(report, pars, cn);
      // Visualizando el Reporte
      JasperViewer viewer = new JasperViewer(print, false);
      viewer.setTitle("LISTADO DE CLIENTES");
      viewer.setVisible(true);
    } catch (Exception e) {
      Mensaje.error(rootPane, e.getMessage());
    } finally{
      try {
        cn.close();
      } catch (Exception e) {
      }
    }
  }//GEN-LAST:event_menuReportesClientesActionPerformed

  private void menuReportesClientes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesClientes2ActionPerformed
    cargarVentana(ReporteClientes2View.class);
  }//GEN-LAST:event_menuReportesClientes2ActionPerformed

  private void menuProcesosRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcesosRetiroActionPerformed
    cargarVentana(RetiroView.class);
  }//GEN-LAST:event_menuProcesosRetiroActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MainView().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuItem aboutMenuItem;
  private javax.swing.JMenuItem contentMenuItem;
  private javax.swing.JMenuItem copyMenuItem;
  private javax.swing.JMenuItem cutMenuItem;
  private javax.swing.JMenuItem deleteMenuItem;
  private javax.swing.JDesktopPane desktopPane;
  private javax.swing.JMenu editMenu;
  private javax.swing.JMenuItem exitMenuItem;
  private javax.swing.JMenu fileMenu;
  private javax.swing.JMenu helpMenu;
  private javax.swing.JMenuBar menuBar;
  private javax.swing.JMenu menuProcesos;
  private javax.swing.JMenuItem menuProcesosCrearCuenta;
  private javax.swing.JMenuItem menuProcesosDeposito;
  private javax.swing.JMenuItem menuProcesosRetiro;
  private javax.swing.JMenuItem menuProcesosTransferencia;
  private javax.swing.JMenu menuReportes;
  private javax.swing.JMenuItem menuReportesClientes;
  private javax.swing.JMenuItem menuReportesClientes2;
  private javax.swing.JMenu menuTablas;
  private javax.swing.JMenuItem menuTablasCliente;
  private javax.swing.JMenuItem menuTablasSucursales;
  private javax.swing.JMenuItem openMenuItem;
  private javax.swing.JMenuItem pasteMenuItem;
  private javax.swing.JMenuItem saveAsMenuItem;
  private javax.swing.JMenuItem saveMenuItem;
  // End of variables declaration//GEN-END:variables

  private void cargarVentana(Class<?> aClass) {
    try {
      JInternalFrame view = null;
      // Buscar objeto
      for (JInternalFrame bean : desktopPane.getAllFrames()) {
        if (aClass.isInstance(bean)) {
          view = bean;
          break;
        }
      }
      // Crear instancia
      if (view == null) {
        view = (JInternalFrame) Class.forName(aClass.getName()).newInstance();
        desktopPane.add(view);
        view.setVisible(true);
      }
      // Activar formulario
      view.setSelected(true);
      view.setIcon(false);
    } catch (Exception e) {
    }
  }

}
