/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.egcc.eureka.app.view;

import java.io.InputStream;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import pe.egcc.eureka.app.db.AccesoDB;
import pe.egcc.eureka.app.util.Mensaje;
import pe.egcc.eureka.app.util.ReportViewInternal;

/**
 *
 * @author Gustavo Coronel
 */
public class ReporteClientes2View extends javax.swing.JInternalFrame {

  /**
   * Creates new form ReporteClientes2View
   */
  public ReporteClientes2View() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    txtNombre = new javax.swing.JTextField();
    btnEjecutar = new javax.swing.JButton();
    panelRepo = new javax.swing.JPanel();

    setClosable(true);
    setIconifiable(true);
    setMaximizable(true);
    setResizable(true);
    setTitle("REPORTE DE CLIENTES 2");

    jLabel1.setText("Nombre");

    btnEjecutar.setText("Ejecutar");
    btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEjecutarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout panelRepoLayout = new javax.swing.GroupLayout(panelRepo);
    panelRepo.setLayout(panelRepoLayout);
    panelRepoLayout.setHorizontalGroup(
      panelRepoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
    panelRepoLayout.setVerticalGroup(
      panelRepoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 336, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(panelRepo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(34, 34, 34)
            .addComponent(btnEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 264, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addComponent(btnEjecutar, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(panelRepo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
    Connection cn = null;
    try {
      // El objeto Connection
      cn = AccesoDB.getConnection();
      // Parametros
      Map pars = new HashMap();
      // logo
      String logo = "/pe/egcc/eureka/app/img/logo3.gif";
      InputStream logoStream = Class.class.getResourceAsStream(logo);
      pars.put("LOGO", logoStream);
      pars.put("NOMBRE", "%" + txtNombre.getText() + "%");
      // Archivo JRXML
      String archivo = "/pe/egcc/eureka/app/reports/listadoClientes2.jrxml";
      InputStream archivoStream = Class.class.getResourceAsStream(archivo);
      // Compilación y ejecución
      JasperReport report = JasperCompileManager.compileReport(archivoStream);
      JasperPrint print = JasperFillManager.fillReport(report, pars, cn);
      // Visualizando el Reporte
      panelRepo.removeAll();
      ReportViewInternal view = new ReportViewInternal("REPORTE DE CLIENTES");
      panelRepo.add(view);
      view.setReporte(print);
      view.setVisible(true);
      view.setMaximum(true);
    } catch (Exception e) {
      Mensaje.error(rootPane, e.getMessage());
    } finally{
      try {
        cn.close();
      } catch (Exception e) {
      }
    }

  }//GEN-LAST:event_btnEjecutarActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnEjecutar;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel panelRepo;
  private javax.swing.JTextField txtNombre;
  // End of variables declaration//GEN-END:variables
}
